# _config.yml

title: 地平线
author: 王维
description: "欢迎来到我的个人网站"
lang: zh-CN
timezone: Asia/Shanghai

remote_theme: daattali/beautiful-jekyll

plugins:
  - jekyll-remote-theme

url: "https://seamoonappear.github.io"
baseurl: "/blog"  # 仓库名是 blog

social:
  name: 王维
  email: "your-email@example.com"
  links:
    - "https://github.com/seamoonappear"

# ✅ 含下拉子菜单的导航栏配置
nav:
  - title: "首页"
    url: /
  - title: "博客"
    sublinks:
      - title: "全部文章"
        url: /tabs/blog/
      - title: "技术"
        url: /tabs/tech/
      - title: "生活"
        url: /tabs/life/
  - title: "消费"
    sublinks:
      - title: "书影音"
        url: /tabs/media/
      - title: "兴趣"
        url: /tabs/hobby/
  - title: "照片"
    sublinks:
      - title: "风景"
        url: /tabs/photo/
      - title: "旅行"
        url: /tabs/stop/
  - title: "关于我"
    url: /tabs/about/

# 页面配置
show_downloads: false

# ✅ 已去除谷歌统计与评论功能
google_analytics: ""
disqus_shortname: ""

markdown: kramdown
permalink: pretty