# 基本信息
title: 地平线
author: 王维
description: "欢迎来到我的个人网站"
lang: zh-CN
timezone: Asia/Shanghai

# 正确的 Beautiful Jekyll 主题设置
remote_theme: daattali/beautiful-jekyll

# 插件（GitHub Pages 支持）
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# 网站地址设置（请确认仓库名）
# 如果仓库名是 seamoonappear.github.io，则保持为空
url: "https://seamoonappear.github.io"
baseurl: "/blog" # 若是 blog 子库则填 "/blog"

# 导航栏
navbar:
  title: "地平线"
  logo:
    image: /assets/img/avatar.jpg
    alt: 王维
    link: /about/
  links:
    - title: "博客"
      url: /blog/
    - title: "媒体"
      url: /media/
      children:
        - title: "书籍"
          url: /media/books/
        - title: "音乐"
          url: /media/music/
        - title: "电影"
          url: /media/movies/
        - title: "停留"
          url: /media/stops/
        - title: "爱好"
          url: /media/hobby/
    - title: "关于我"
      url: /about/

# 首页设置（混合布局）
show_excerpts: true
paginate: 6
paginate_path: "/page:num/"
excerpt_separator: "<!--more-->"
layout: home

# 社交链接（可选）
social-network-links:
  github: seamoonappear

# 不使用谷歌分析
google_analytics: false

# 文件和构建排除
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - tmp

# Markdown 设置
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false