# _config.yml

title: 地平线
author: 王维
description: "欢迎来到我的个人网站"
lang: zh-CN
timezone: Asia/Shanghai

# 使用 Beautiful Jekyll 主题
remote_theme: daattali/beautiful-jekyll

# 插件配置
plugins:
  - jekyll-remote-theme

# 网站 URL 设置（仓库名是 blog）
url: "https://seamoonappear.github.io"
baseurl: "/blog"  # ✅ 保留这一行

# 社交链接
social:
  name: 王维
  email: "your-email@example.com"
  links:
    - "https://github.com/seamoonappear"

# ✅ 修正后的导航栏路径（不要重复写 /blog）
nav:
  - title: "首页"
    url: /
  - title: "博客"
    url: /tabs/blog/
  - title: "消费"
    url: /tabs/media/
  - title: "照片"
    url: /tabs/photo/
  - title: "驻足"
    url: /tabs/stop/
  - title: "关于我"
    url: /tabs/about/

# 页面配置
show_downloads: false
google_analytics: ""
disqus_shortname: ""

# 构建设置
markdown: kramdown
permalink: pretty