# ---------------------------
# 基本信息
# ---------------------------
title: "地平线"
description: "纪委的个人博客 · 学习 感悟 探索"
author: "Seamoonappear"
url: "https://seamoonappear.github.io/blog"

# ---------------------------
# 使用 Beautiful Jekyll 主题
# ---------------------------
remote_theme: daattali/beautiful-jekyll

plugins:
  - jekyll-remote-theme

# ---------------------------
# 页面与社交信息
# ---------------------------
navbar-links:
  首页: "index.md"
  博客: "posts"
  关于我: "about.md"

social-network-links:
  github: seamoonappear
  rss: true

# ---------------------------
# 外观设置
# ---------------------------
avatar: "/assets/img/avatar.jpg"  # 头像路径
favicon: "/assets/img/favicon.png"
footer: "© 2025 Seamoonappear | Powered by Beautiful Jekyll"
