# _config.yml

title: 地平线
author: 王维
description: "欢迎来到我的个人网站"
lang: zh-CN
timezone: Asia/Shanghai

# 使用正确的 Beautiful Jekyll 远程主题
remote_theme: daattali/beautiful-jekyll

# 插件配置
plugins:
  - jekyll-remote-theme

# 网站URL - 根据你的用户名和仓库名设置
url: "https://seamoonappear.github.io"
baseurl: "/blog"  # 因为仓库名是blog，不是用户名.github.io

# 社交链接
social:
  name: 王维
  email: "your-email@example.com"  # 请修改为你的邮箱
  links:
    - "https://github.com/seamoonappear"  # 你的GitHub主页
    # 可以添加更多社交链接
    # - "https://twitter.com/yourusername"
    # - "https://weibo.com/yourusername"

# 修正后的导航栏配置 - 指向 tabs 目录下的页面
nav:
  - title: "首页"
    url: /
  - title: "博客"
    url: /blog/tabs/blog/
  - title: "消费"
    url: /blog/tabs/media/
  - title: "照片"
    url: /blog/tabs/photo/
  - title: "驻足"
    url: /blog/tabs/stop/
  - title: "关于我"
    url: /blog/tabs/about/

# 页面配置
show_downloads: false
google_analytics: ""
disqus_shortname: ""

# 构建设置
markdown: kramdown
permalink: pretty