# 基本站点信息
title: 地平线
author: 王维
description: "欢迎来到我的个人网站"
lang: zh-CN
timezone: Asia/Shanghai

# 使用 Beautiful Jekyll 官方远程主题
remote_theme: daattali/beautiful-jekyll

# 启用的插件
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# 部署路径设置
url: "https://seamoonappear.github.io"
baseurl: "/blog"  # 若是主库 seamoonappear.github.io 就改成 ""

# 网站导航栏
navbar:
  title: "地平线"
  logo:
    image: /assets/img/avatar.jpg
    alt: 王维
    link: /tabs/about/
  links:
    - title: "博客"
      url: /tabs/blog/
    - title: "媒体"
      url: /tabs/media/
      children:
        - title: "书籍"
          url: /tabs/media/books/
        - title: "音乐"
          url: /tabs/media/music/
        - title: "电影"
          url: /tabs/media/movies/
        - title: "停留"
          url: /tabs/stop/
        - title: "爱好"
          url: /tabs/media/hobby/
    - title: "关于我"
      url: /tabs/about/

# 首页布局设置（混合布局：封面 + 博客列表）
show_excerpts: true
paginate: 6
paginate_path: "/page:num/"
excerpt_separator: "<!--more-->"
layout: home

# 社交链接
social-network-links:
  github: seamoonappear

# 禁用谷歌分析
google_analytics: false

# 构建排除项
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - tmp

# Markdown 设置
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false