# _config.yml

title: 地平线
author: 王维
theme: beautiful-jekyll
lang: zh-CN
timezone: Asia/Shanghai

# 导航栏配置
nav:
  - title: "首页"
    url: /
  - title: "博客"
    url: /blog/
  - title: "消费"
    url: /media/
  - title: "照片"
    url: /photo/
  - title: "驻足"
    url: /stop/
  - title: "关于"
    url: /about/