# _config.yml

title: 地平线
author: 王维
lang: zh-CN
timezone: Asia/Shanghai

# 使用 remote_theme 代替本地 theme
remote_theme: mmistakes/beautiful-jekyll@master
plugins:
  - jekyll-remote-theme

# 导航栏配置
nav:
  - title: "首页"
    url: /
  - title: "博客"
    url: /blog/
  - title: "消费"
    url: /media/
  - title: "照片"
    url: /photo/
  - title: "驻足"
    url: /stop/
  - title: "关于我"
    url: /about/